/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ht_fz;

import java.awt.CardLayout;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    String Nametxt1="";
    String Nametxt2="";
    String Nametxt3="";
    String Nametxt4="";
    int a;
    int b;
    double result4;
    double result1;
    double result2;
    double result3;
    int day1;
    int day2;
    int day3;
    int day4;
    int out;
    String status11;
    String status12;
    String status13;
    public Main() {
        initComponents();
         c1 = (CardLayout) jPanel1.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        totalarea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Room1 = new javax.swing.JRadioButton();
        Room2 = new javax.swing.JRadioButton();
        Room3 = new javax.swing.JRadioButton();
        Room4 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        option2 = new javax.swing.JCheckBox();
        option1 = new javax.swing.JCheckBox();
        Bookingbutton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        daytxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        countday = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        status1 = new javax.swing.JTextField();
        status2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        status3 = new javax.swing.JTextField();
        status4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jselect = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        inputmonny = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtendtotal = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setTitle("Panda Hotal");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ht_fz/Image/panda (2).png"))); // NOI18N
        jLabel3.setText("\n\n\n\n\n\n\n\n      PANDA HOTEL");
        jPanel1.add(jLabel3, "card2");

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("จองห้องพัก");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("ชื่อลูกค้า");

        nametxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("ระยะเวลาการเข้าพัก");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ht_fz/Image/door (3).png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("สถานะห้อง");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ht_fz/Image/door (3).png"))); // NOI18N

        totalarea.setBackground(new java.awt.Color(0, 0, 0));
        totalarea.setColumns(20);
        totalarea.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalarea.setForeground(new java.awt.Color(255, 255, 255));
        totalarea.setRows(5);
        totalarea.setFocusable(false);
        jScrollPane1.setViewportView(totalarea);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ht_fz/Image/door (3).png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ht_fz/Image/door (3).png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("ROOM 1");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("ROOM 2");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("ROOM 3");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("ROOM 4");

        Room1.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(Room1);
        Room1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Room1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Room1MouseClicked(evt);
            }
        });

        Room2.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(Room2);
        Room2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Room2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Room2MouseClicked(evt);
            }
        });

        Room3.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(Room3);
        Room3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Room3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Room3MouseClicked(evt);
            }
        });

        Room4.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(Room4);
        Room4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Room4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Room4MouseClicked(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setText("เพิ่มเติม");

        option2.setBackground(new java.awt.Color(255, 204, 204));
        option2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        option2.setText("เพิ่มเตียงนอนเสริม");

        option1.setBackground(new java.awt.Color(255, 204, 204));
        option1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        option1.setText("บริการซักรีด");

        Bookingbutton.setBackground(new java.awt.Color(255, 255, 255));
        Bookingbutton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Bookingbutton.setText("ตกลง");
        Bookingbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingbuttonMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("ล้าง");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jTextArea3.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);
        jTextArea3.setFocusable(false);
        jScrollPane3.setViewportView(jTextArea3);

        daytxt.setFocusable(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Out");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("กรุณาเลือกห้องด้านล่าง");

        countday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        countday.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("*ราคาต่อวัน");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("วัน");

        status1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        status1.setText("ว่าง");

        status2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        status2.setText("ว่าง");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Out");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText(" Status Room1");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Status Room2");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("Status Room3");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("Status Room4");

        status3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        status3.setText("ว่าง");

        status4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        status4.setText("ว่าง");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Out");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("Out");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(Room3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Room4)
                        .addGap(181, 181, 181))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(Bookingbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton4)
                                            .addGap(90, 90, 90)
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButton5))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addComponent(jLabel16)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel17)
                                            .addGap(94, 94, 94)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(86, 86, 86)
                                                .addComponent(jLabel13)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton3))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(106, 106, 106))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(Room1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Room2)
                                        .addGap(144, 144, 144)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(43, 43, 43)
                                        .addComponent(option1)
                                        .addGap(18, 18, 18)
                                        .addComponent(option2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(countday, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(daytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20))))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(status2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(daytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(countday, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(option1)
                            .addComponent(option2)
                            .addComponent(jLabel23))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bookingbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Room2)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addGap(9, 9, 9))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1))
                                .addGap(18, 18, 18)
                                .addComponent(Room1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(9, 9, 9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Room3)
                            .addComponent(Room4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(status2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(status3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(status4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        jPanel1.add(jPanel2, "card3");

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel24.setText("ชำระเงิน");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("เลือกห้อง");

        jselect.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jselect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ROOM1", "ROOM2", "ROOM3", "ROOM4", " " }));
        jselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jselectActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("รายละเอียด");

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setText("ยอดชำระ");

        inputmonny.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setText("รับเงินมา");

        txtendtotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total.setFocusable(false);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setText("เงินทอน");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("คำนวน");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setText("ล้าง");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setText("บาท");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel29.setText("บาท");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel30.setText("บาท");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(738, 738, 738)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(457, 457, 457)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jselect, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel27)
                        .addComponent(jLabel26)))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(inputmonny)
                    .addComponent(txtendtotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addGap(127, 127, 127))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel24)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtendtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(inputmonny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel22)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel30))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton7)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, "card4");

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(null);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(1000, 48));

        jMenu1.setBackground(new java.awt.Color(255, 255, 153));
        jMenu1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu1.setForeground(new java.awt.Color(255, 0, 153));
        jMenu1.setText("     HOME");
        jMenu1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setMinimumSize(new java.awt.Dimension(30, 19));
        jMenu1.setPreferredSize(new java.awt.Dimension(200, 48));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu2.setForeground(new java.awt.Color(0, 51, 255));
        jMenu2.setText("    BOOKING");
        jMenu2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setPreferredSize(new java.awt.Dimension(250, 48));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu3.setForeground(new java.awt.Color(0, 153, 51));
        jMenu3.setText("    PAYMENT");
        jMenu3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(252, 48));
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu4.setForeground(new java.awt.Color(255, 0, 102));
        jMenu4.setText("   EXIT");
        jMenu4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 48));
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        System.exit(0);
        super.dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
         c1.show(jPanel1, "card3");
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
         c1.first(jPanel1);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        c1.show(jPanel1, "card4");
    }//GEN-LAST:event_jMenu3MouseClicked
 
    private void BookingbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingbuttonMouseClicked
       
       ///////////////////////////////////ห้อง 1 //////////////////////////////////
       if (Room1.isSelected()) {
       
       String status = status1.getText();
       if(status.equals("ว่าง")){// ไม่มีประวัติจะให้ทำ
       Nametxt1 = nametxt.getText();
       if (Nametxt1.equals("")) {
            JOptionPane.showMessageDialog(null, "กรุณาใส่ชื่อ", "กรอกชื่อ",JOptionPane.ERROR_MESSAGE);  
            
       }    
       else{
       status1.setText("ไม่ว่าง");
       
       day1 = (Integer)countday.getValue();
       int total = 0;
       int item1 = 0;
       int item2 = 0;
       totalarea.append("เจ้าของห้อง:  "+Nametxt1);
       totalarea.append("\n");
       if(Room1.isSelected()){
           totalarea.append("ค่าห้อง   -> Price  500 ฿ พักอยู่: "+day1+"วัน");
           total = 500*day1;
       }if (Room2.isSelected()){
           totalarea.append("ค่าห้อง   -> Price  1,500 ฿พักอยู่: "+day1+"วัน");
           total = 1500*day1;
       }if (Room3.isSelected()){
           totalarea.append("ค่าห้อง  -> Price  2,500 ฿พักอยู่: "+day1+"วัน");
           total = 2500*day1;
       }if(Room4.isSelected()) {
           totalarea.append("ค่าห้อง   -> Price  4,000 ฿พักอยู่: "+day1+"วัน");
           total = 4000*day1;
       }
       if(option1.isSelected()){
           totalarea.append("\n");
           totalarea.append("ค่าบริการซักรีด   -> Price  500 ฿");
           item1 = 500;
           a=1;
       }if (option2.isSelected()){
           totalarea.append("\n");
           totalarea.append("เพิ่มเตียงนอนเสริม   -> Price  700 ฿");
           item2 = 700;
           b=1;
       }
       result1 = total+item1+item2 ;
       totalarea.append("\n");
       totalarea.append("ยอดชำระรวม : "+result1);
       totalarea.append("\n");
       totalarea.append("\n");
       
      
       jTextArea3.append("\nRoom1   ชื่อผู้จอง :   "+Nametxt1);
       jTextArea3.append("\n");
       
         
       }
       }//เช็คห้องซ้ำ
       else{
       JOptionPane.showMessageDialog(null, "มีคนจองห้องนี้แล้ว", "กรอกชื่อ",JOptionPane.ERROR_MESSAGE);
       
       }
       
       }// จบ
   
        ///////////////////////////////////ห้อง 2 //////////////////////////////////
       if (Room2.isSelected()) {
       String status = status2.getText();
       if(status.equals("ว่าง")){// ไม่มีประวัติจะให้ทำ
        Nametxt2 = nametxt.getText();
       if (Nametxt2.equals("")) {
            JOptionPane.showMessageDialog(null, "กรุณาใส่ชื่อ", "กรอกชื่อ",JOptionPane.ERROR_MESSAGE);  
            
       }    
       else{
       status2.setText("ไม่ว่าง");
       
       day2 = (Integer)countday.getValue();
       int total = 0;
       int item1 = 0;
       int item2 = 0;
       totalarea.append("เจ้าของห้อง:  "+Nametxt2);
       totalarea.append("\n");
       if(Room1.isSelected()){
           totalarea.append("ค่าห้อง   -> Price  500 ฿ พักอยู่: "+day2+"วัน");
           total = 500*day2;
       }if (Room2.isSelected()){
           totalarea.append("ค่าห้อง   -> Price  1,500 ฿พักอยู่: "+day2+"วัน");
           total = 1500*day2;
       }if (Room3.isSelected()){
           totalarea.append("ค่าห้อง  -> Price  2,500 ฿พักอยู่: "+day2+"วัน");
           total = 2500*day2;
       }if(Room4.isSelected()) {
           totalarea.append("ค่าห้อง   -> Price  4,000 ฿พักอยู่: "+day2+"วัน");
           total = 4000*day2;
       }
       if(option1.isSelected()){
           totalarea.append("\n");
           totalarea.append("ค่าบริการซักรีด   -> Price  500 ฿");
           item1 = 500;
           a=1;
       }if (option2.isSelected()){
           totalarea.append("\n");
           totalarea.append("เพิ่มเตียงนอนเสริม   -> Price  700 ฿");
           item2 = 700;
           b=1;
       }
       result2 = total+item1+item2 ;
       totalarea.append("\n");
       totalarea.append("ยอดชำระรวม : "+result2);
       totalarea.append("\n");
       totalarea.append("\n");
       
      
       jTextArea3.append("\nRoom2   ชื่อผู้จอง :   "+Nametxt2);
       jTextArea3.append("\n");
       
         
       }
       }//เช็คห้องซ้ำ
       else{
       JOptionPane.showMessageDialog(null, "มีคนจองห้องนี้แล้ว", "กรอกชื่อ",JOptionPane.ERROR_MESSAGE);
       
       }
       
       }// จบ
       
         ///////////////////////////////////ห้อง 3 //////////////////////////////////
       if (Room3.isSelected()) {
       String status = status3.getText();
       if(status.equals("ว่าง")){// ไม่มีประวัติจะให้ทำ
       Nametxt3 = nametxt.getText();
       if (Nametxt3.equals("")) {
            JOptionPane.showMessageDialog(null, "กรุณาใส่ชื่อ", "กรอกชื่อ",JOptionPane.ERROR_MESSAGE);  
            
       }    
       else{
       status3.setText("ไม่ว่าง");
       
       day3 = (Integer)countday.getValue();
       int total = 0;
       int item1 = 0;
       int item2 = 0;
       totalarea.append("เจ้าของห้อง:  "+Nametxt3);
       totalarea.append("\n");
       if(Room1.isSelected()){
           totalarea.append("ค่าห้อง   -> Price  500 ฿ พักอยู่: "+day3+"วัน");
           total = 500*day3;
       }if (Room2.isSelected()){
           totalarea.append("ค่าห้อง   -> Price  1,500 ฿พักอยู่: "+day3+"วัน");
           total = 1500*day3;
       }if (Room3.isSelected()){
           totalarea.append("ค่าห้อง  -> Price  2,500 ฿พักอยู่: "+day3+"วัน");
           total = 2500*day3;
       }if(Room4.isSelected()) {
           totalarea.append("ค่าห้อง   -> Price  4,000 ฿พักอยู่: "+day3+"วัน");
           total = 4000*day3;
       }
       if(option1.isSelected()){
           totalarea.append("\n");
           totalarea.append("ค่าบริการซักรีด   -> Price  500 ฿");
           item1 = 500;
           a=1;
       }if (option2.isSelected()){
           totalarea.append("\n");
           totalarea.append("เพิ่มเตียงนอนเสริม   -> Price  700 ฿");
           item2 = 700;
           b=2;
       }
       result3 = total+item1+item2 ;
       totalarea.append("\n");
       totalarea.append("ยอดชำระรวม : "+result3);
       totalarea.append("\n");
       totalarea.append("\n");
       
      
       jTextArea3.append("\nRoom3   ชื่อผู้จอง :   "+Nametxt3);
       jTextArea3.append("\n");
       
         
       }
       }//เช็คห้องซ้ำ
       else{
       JOptionPane.showMessageDialog(null, "มีคนจองห้องนี้แล้ว", "กรอกชื่อ",JOptionPane.ERROR_MESSAGE);
       
       }
       
       }// จบ
       //////////////////////////////////ห้อง 4 ///////////////////////////////////
       
       if (Room4.isSelected()) {
       String status = status4.getText();
       if(status.equals("ว่าง")){// ไม่มีประวัติจะให้ทำ
       Nametxt4 = nametxt.getText();
       if (Nametxt4.equals("")) {
            JOptionPane.showMessageDialog(null, "กรุณาใส่ชื่อ", "กรอกชื่อ",JOptionPane.ERROR_MESSAGE);  
            
       }    
       else{
       status4.setText("ไม่ว่าง");
       
       day4 = (Integer)countday.getValue();
       int total = 0;
       int item1 = 0;
       int item2 = 0;
       totalarea.append("เจ้าของห้อง:  "+Nametxt4);
       totalarea.append("\n");
       if(Room1.isSelected()){
           totalarea.append("ค่าห้อง   -> Price  500 ฿ พักอยู่: "+day4+"วัน");
           total = 500*day4;
       }if (Room2.isSelected()){
           totalarea.append("ค่าห้อง   -> Price  1,500 ฿พักอยู่: "+day4+"วัน");
           total = 1500*day4;
       }if (Room3.isSelected()){
           totalarea.append("ค่าห้อง  -> Price  2,500 ฿พักอยู่: "+day4+"วัน");
           total = 2500*day4;
       }if(Room4.isSelected()) {
           totalarea.append("ค่าห้อง   -> Price  4,000 ฿พักอยู่: "+day4+"วัน");
           total = 4000*day4;
       }
       if(option1.isSelected()){
           totalarea.append("\n");
           totalarea.append("ค่าบริการซักรีด   -> Price  500 ฿");
           item1 = 500;
           a=1;
          
       }if (option2.isSelected()){
           totalarea.append("\n");
           totalarea.append("เพิ่มเตียงนอนเสริม   -> Price  700 ฿");
           item2 = 700;
           b=2;
       }
       result4 = total+item1+item2 ;
       totalarea.append("\n");
       totalarea.append("ยอดชำระรวม : "+result4);
       totalarea.append("\n");
       totalarea.append("\n");
       
      
       jTextArea3.append("\nRoom4   ชื่อผู้จอง :   "+Nametxt4);
       jTextArea3.append("\n");
       
         
       }
       }//เช็คห้องซ้ำ
       else{
       JOptionPane.showMessageDialog(null, "มีคนจองห้องนี้แล้ว", "กรอกชื่อ",JOptionPane.ERROR_MESSAGE);
       
       }
       
       }// จบ
        
        
        
        
        
        
    }//GEN-LAST:event_BookingbuttonMouseClicked

    private void Room1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Room1MouseClicked
        daytxt.setText("ห้องเดี่ยว 500 บาท");
        
    }//GEN-LAST:event_Room1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        status1.setText("ว่าง");
        jTextArea3.append("\n");
        jTextArea3.append("Room1 => checkout");
        out=1;
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        option1.setSelected(false);
        option2.setSelected(false);
        nametxt.setText("");
        daytxt.setText("");
        countday.setValue(1);
        totalarea.setName("");
        
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void Room2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Room2MouseClicked
        
        daytxt.setText("ห้องเตียงคู่ 1,500 บาท");
    }//GEN-LAST:event_Room2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        status2.setText("ว่าง");
        jTextArea3.append("\n");
        jTextArea3.append("Room2 => checkout");
        out=1;
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void Room3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Room3MouseClicked
        daytxt.setText("ห้องเตียงคู่+ห้องโถง 2,500 บาท");
    }//GEN-LAST:event_Room3MouseClicked

    private void Room4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Room4MouseClicked
        daytxt.setText("ห้องหรู+ห้องโถง 4,000 บาท");
    }//GEN-LAST:event_Room4MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        status3.setText("ว่าง");
        jTextArea3.append("\n");
        jTextArea3.append("Room3 => checkout");
        out=1;
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        status4.setText("ว่าง");
        jTextArea3.append("\n");
        jTextArea3.append("Room4 => checkout");
        out=1;
    }//GEN-LAST:event_jButton5MouseClicked

    private void jselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jselectActionPerformed
        if(jselect.getSelectedIndex()==0){
            if(out==1){
            String status = status1.getText();
            if(status.equals("ว่าง")){
            jTextArea1.append("\nเจ้าของห้อง: "+Nametxt1);
            jTextArea1.append("\nค่าห้อง   -> Price  500 ฿    "+day1+"  วัน");
            if(a==1)
                jTextArea1.append("\nค่าบริการซักรีด   -> Price  500 ฿");
            if(b==1)
                jTextArea1.append("\nเพิ่มเตียงนอนเสริม   -> Price  700 ฿");
            totalprice = ""+result1;
            txtendtotal.setText(totalprice);
            out=0; 
            }else{ JOptionPane.showMessageDialog(null, "ห้องนี้ยังไม่ถูก Out", "ผิดพลาด",JOptionPane.ERROR_MESSAGE);
            }
            }else{
            JOptionPane.showMessageDialog(null, "กด Out จากห้องก่อน", "ผิดพลาด",JOptionPane.ERROR_MESSAGE);
            }
            
                     
        }
          if(jselect.getSelectedIndex()==1){
            if(out==1){
            String status = status2.getText();
            if(status.equals("ว่าง")){
            jTextArea1.append("\nเจ้าของห้อง: "+Nametxt2);
            jTextArea1.append("\nค่าห้อง   -> Price  1,000    "+day2+"  วัน");
            if(a==1)
                jTextArea1.append("\nค่าบริการซักรีด   -> Price  500 ฿");
            if(b==1)
                jTextArea1.append("\nเพิ่มเตียงนอนเสริม   -> Price  700 ฿");
            totalprice = ""+result2;
            txtendtotal.setText(totalprice);
            out=0; 
            }else{ JOptionPane.showMessageDialog(null, "ห้องนี้ยังไม่ถูก Out", "ผิดพลาด",JOptionPane.ERROR_MESSAGE);
            }
            }else{
            JOptionPane.showMessageDialog(null, "กด Out จากห้องก่อน", "ผิดพลาด",JOptionPane.ERROR_MESSAGE);
            }
            
        }
            if(jselect.getSelectedIndex()==2){
            if(out==1){
           String status = status3.getText();
            if(status.equals("ว่าง")){
            jTextArea1.append("\nเจ้าของห้อง: "+Nametxt3);
            jTextArea1.append("\nค่าห้อง   -> Price  2,500    "+day3+"  วัน");
            if(a==1)
                jTextArea1.append("\nค่าบริการซักรีด   -> Price  500 ฿");
            if(b==1)
                jTextArea1.append("\nเพิ่มเตียงนอนเสริม   -> Price  700 ฿");
            totalprice = ""+result3;
            txtendtotal.setText(totalprice);
            out=0; 
            }else{ JOptionPane.showMessageDialog(null, "ห้องนี้ยังไม่ถูก Out", "ผิดพลาด",JOptionPane.ERROR_MESSAGE);
            }
            }else{
            JOptionPane.showMessageDialog(null, "กด Out จากห้องก่อน", "ผิดพลาด",JOptionPane.ERROR_MESSAGE);
            }
            
        }
           if(jselect.getSelectedIndex()==3){
            if(out==1){
            String status = status4.getText();
            if(status.equals("ว่าง")){
            jTextArea1.append("\nเจ้าของห้อง: "+Nametxt4);
            jTextArea1.append("\nค่าห้อง   -> Price  4,000    "+day4+"  วัน");
            if(a==1)
                jTextArea1.append("\nค่าบริการซักรีด   -> Price  500 ฿");
            if(b==1)
                jTextArea1.append("\nเพิ่มเตียงนอนเสริม   -> Price  700 ฿");
            totalprice = ""+result4;
            txtendtotal.setText(totalprice);
            out=0; 
            }else{ JOptionPane.showMessageDialog(null, "ห้องนี้ยังไม่ถูก Out", "ผิดพลาด",JOptionPane.ERROR_MESSAGE);
            }
            }else{
               JOptionPane.showMessageDialog(null, "กด out จากห้องก่อน", "ผิดพลาด",JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
    }//GEN-LAST:event_jselectActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int input = Integer.parseInt(inputmonny.getText());;
        if(jselect.getSelectedIndex()==0){
        total.setText(String.valueOf(input-result1));
        }
        if(jselect.getSelectedIndex()==1){
        total.setText(String.valueOf(input-result2));}
        if(jselect.getSelectedIndex()==2){
        total.setText(String.valueOf(input-result3));}
        if(jselect.getSelectedIndex()==3){
        total.setText(String.valueOf(input-result4));}
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTextArea1.setText("");
        txtendtotal.setText("");
        inputmonny.setText("");
        total.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

 
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bookingbutton;
    private javax.swing.JRadioButton Room1;
    private javax.swing.JRadioButton Room2;
    private javax.swing.JRadioButton Room3;
    private javax.swing.JRadioButton Room4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSpinner countday;
    private javax.swing.JTextField daytxt;
    private javax.swing.JTextField inputmonny;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JComboBox jselect;
    private javax.swing.JTextField nametxt;
    private javax.swing.JCheckBox option1;
    private javax.swing.JCheckBox option2;
    private javax.swing.JTextField status1;
    private javax.swing.JTextField status2;
    private javax.swing.JTextField status3;
    private javax.swing.JTextField status4;
    private javax.swing.JTextField total;
    private javax.swing.JTextArea totalarea;
    private javax.swing.JTextField txtendtotal;
    // End of variables declaration//GEN-END:variables
    private CardLayout c1;
    String totalprice = "";

}
